### ISSUE TITLE
paste URL from clipboard?

### ISSUE THREAD

**Issue by gliptak** [lusakasa/saka-key#11]
Is it possible to load the URL from the clipboard? Thanks

**Comment by eejdoowad** [comment]
Is loading the URL into the current tab enough?

Or do you want the ability to load the URL into the current tab, a new foreground tab, a new background tab, a new window, or an incognito window?

**Comment by gliptak** [comment]
@eejdoowad Loading the URL those various ways makes this orthogonal.

http://saka-key.lusakasa.com/tutorial/clicking_and_link_hints.html

While current tab is the most useful, others would also be welcome. Thanks

**Comment by eejdoowad** [comment]
I'll make another release in the next couple days with this feature. Do you have preferred keybindings for the following commands? I've included the bindings I'm currently leaning towards.

* the current tab - y, f
* a new foreground tab - y, shift+f
* a new background tab - y, b
* a new window - y, n
* an incognito window - y, shift+n

**Comment by gliptak** [comment]
Those looks consistent with current mappings. You are the best person to determine :)

I'm adding some thoughts on the mapping at https://github.com/lusakasa/saka-key/issues/12

Thanks

**Comment by eejdoowad** [comment]
I've published v1.16r which contains the requested features. Thanks!
