### ISSUE TITLE
Firefox 57: flash of unstyled content

### ISSUE THREAD

**Issue by vincentbernat** [lusakasa/saka-key#121]
Hello!

I thought this was a problem with the beta version of Firefox, but the problem remains on the stable one. It only happens when Saka Key is enabled. On many pages, the page is first rendered unstyled, then the style is applied. This is very fast but also very annoying. For example, on GitHub, click on the top tabs "Pull requests", "Issues", "Marketplace", "Explore". Each time, the page is rendered without style then shortly after (< 100ms) with the style. Even, with a warm cache.

I thought it may be because Saka Key put its `div` element before the `head`.

If you can't reproduce this, I can provide a video of the problem.

**Comment by asb** [comment]
I also saw this problem (FF57 on Arch Linux). Observed on news.ycombinator.com.

**Comment by joefiesta** [comment]
This is not just FF57.   I'm at FF54 and I experience the same thing.  I'm at 1.25.2 Saka Key.

**Comment by ddddavidmartin** [comment]
I'm seeing the same on OSX. It is most apparent on https://news.ycombinator.com/news where all text flashes blue for a moment after (re)loading the page.

**Comment by eejdoowad** [comment]
Thanks for the bug reports. Duplicates #30. I tried the fix I described at the end of #30 without success. Still trying to figure out the cause. If you have any updates that could help, please post there.
