### ISSUE TITLE
FEATURE REQUEST: Button to clear/delete all keybindings at once

### ISSUE THREAD

**Issue by DanBondarenko** [lusakasa/saka-key#13]
Hi! Thanks for the wonderful extension. 

As I do not use all of the shortcuts that Saka Key offers and I use them with keybindings which differ quite a bit from the default ones, I have to delete all of the existing (default) keybindings which Saka Key provides and then create new keybindings for the shortcuts that I actually use. 

This process would be greatly shortened if there was a button on the options page with which I could automatically clear/delete all of the keybindings. After that I could create the keybindings for the shortcuts of which I have use. 

Alternatively, the same could be achieved by clearing all keybinding on the 'New' keybindings profile (when I create a new keybindings profile by selecting 'New' from the menu in the settings card options). This way there would be no keybindings selected on the 'New' settings. I think that would make more sense as well, since there already is an option to 'Duplicate' — there is no need for 'New' to work as a sort of pseudo-'Duplicate'.

**Comment by eejdoowad** [comment]
That's actually how 'New' is supposed to work. I'll make sure this bug is fixed in the next release. Thanks!

**Comment by gliptak** [comment]
@DanBondarenko What are your keybindings modeled after? Could they be of interest to other users of Saka Key? Thanks

**Comment by eejdoowad** [comment]
I've published v1.16r which contains the requested features. Thanks!
