### ISSUE TITLE
Feature request: scroll through address bar suggestions

### ISSUE THREAD

**Issue by plantarum** [lusakasa/saka-key#163]
I would really like to be able to navigate  through the suggestions provided in the address bar without using the arrow keys. Coming from Emacs, it's second nature to hit C-n and C-p to go up and down through that list. Is it possible to add that ability to Saka key?

**Comment by alexherbo2** [comment]
Nope the API doesn’t let manipulate the address bar.

I’m not sure it is possible to bind <kbd>Control</kbd> <kbd>n</kbd> or <kbd>Control</kbd> <kbd>p</kbd> reliably either, as they are browser shortcuts.

**Comment by plantarum** [comment]
Too bad! I wouldn't need it to be C-n, but something other than arrows would have been nice
