### ISSUE TITLE
Allow installing permanently on firefox

### ISSUE THREAD

**Issue by lufte** [lusakasa/saka-key#19]
The current installation instructions for firefox result in the addon only being installed until the browser is closed. Please take a look at my PR for updated instructions.

**Comment by eejdoowad** [comment]
Thanks for the info and PR!

To avoid manifest warnings, I decided to generate different manifests for Chrome and Firefox, and the [Firefox manifest](https://github.com/lusakasa/saka-key/blob/master/manifest/firefox.json) now includes its unique ID! Hopefully this resolves the issue.

BTW, The current recommended install for procedure for firefox is to install the Development Channel directly from the Addons marketplace.

**Comment by lufte** [comment]
Awesome, thanks. Yeah I just now figured where how to install the beta release from the marketplace, much more convinient.
