### ISSUE TITLE
Blacklist of sites

### ISSUE THREAD

**Issue by igorsantos07** [lusakasa/saka-key#192]
This is similar to #180: would be handy to be able to completely disable SakaKey on sites where we're heavy on shortcuts, like Gmail.

**Comment by lonix1** [comment]
Also I want to blacklist sites where saka conflicts with a particular page.

e.g. it doesn't work well with our intranet pages, so I want to blacklist it, so it doesn't add: `saka-gui-root` node to the DOM.

**Comment by neilmacintyre** [comment]
I am going to start working on this issue. My plan is to add a blacklist tab to the options menu.  Blacklisting will be done using regex, to allow both for whole domain and specific page blocking. I will make a pull-request when I have it up and running hopefully sometime next week.

**Comment by lonix1** [comment]
@neilmacintyre Will you push to extensions site? Looking forward to trying this out!

**Comment by neilmacintyre** [comment]
Yeah I have to set up the accounts, but it should be up in the next couple of days.

**Comment by neilmacintyre** [comment]
@igorsantos07 Sorry for the hold up. I just updated the app on Chrome and Firefox extension sites.
