### ISSUE TITLE
doesn't work with xmodmap

### ISSUE THREAD

**Issue by lilydjwg** [lusakasa/saka-key#194]
I've exchanged my Escape key with Caps Lock. It works well in Firefox (and most other applications) except Saka Key.

Here is what Firefox actually says about the events (event 1 is my Escape and others are Caps Lock):

![default](https://user-images.githubusercontent.com/440661/39664363-c59f473c-50b4-11e8-8b28-fc8236bda2b5.png)

Versions:
* latest Arch Linux
* latest Firefox nightly
* latest Saka Key from AMO

**Comment by dov** [comment]
Did you turn off the option "Bind to physical keys (en-US QWERTY) not characters"? I'm using the Dvorak keyboard layout with swapped CapsLock and Ctrl and it works as expected with this option turned off.

**Comment by lilydjwg** [comment]
No, that option wasn't there when I opened this issue. It works well now.
