### ISSUE TITLE
"Open link in foreground/background tab" not working in Firefox

### ISSUE THREAD

**Issue by fturcheti** [lusakasa/saka-key#21]
The commands to "Open links in foreground or background tabs" are not working in Firefox. I can only open links in the same tab.

**Comment by fturcheti** [comment]
Some references from a similar issue in Vimium: 

- Issue: https://github.com/philc/vimium/issues/2510
- Pull request addressing the issue: https://github.com/philc/vimium/pull/2602

**Comment by eejdoowad** [comment]
Thanks for the report. I'll have a fix in shortly.

**Comment by eejdoowad** [comment]
Related changes are in
* https://github.com/lusakasa/saka-key/blob/1502c72c1e7089c911b8da78a9a11619059405a4/src/modes/hints/client/activateHint.js
* https://github.com/lusakasa/saka-key/blob/1502c72c1e7089c911b8da78a9a11619059405a4/src/modes/hints/background/index.js
