### ISSUE TITLE
Saka stopped working

### ISSUE THREAD

**Issue by rypz79** [lusakasa/saka-key#213]
The options/preferences screen (moz-extension://34c1ce59-bd02-4e0b-a70d-4cba1f85e291/options.html) is blank also
![screenshot from 2018-09-06 04-56-33](https://user-images.githubusercontent.com/28814757/45130484-969c4c80-b191-11e8-8c3b-df33797622fe.png)
Can't tell what is the Saka version installed but all my addons are automatically updated.
Firefox v62.0 on Ubuntu 18.04.1 (GNOME 3.28.2)

TNX

**Comment by IOAyman** [comment]
I do confirm this issue! Using Firefox v62.0.1

**Comment by tim-teufel** [comment]
Yes, this is a known issue caused by the last Saka's update. See #212 for more information and workarounds.

**Comment by rypz79** [comment]
It do work in Firefox v62.0 under Windows 10 with the same Saka version 1.25.4beta
<img width="960" alt="saka-key_win10" src="https://user-images.githubusercontent.com/28814757/45158427-a5fcb380-b1ec-11e8-804d-0f2caf93a7fb.png">
