### ISSUE TITLE
Search Open Tabs

### ISSUE THREAD

**Issue by raja** [lusakasa/saka-key#236]
Is it possible to search open tabs. I know vimium has this feature or something like [Quick Tabs](https://chrome.google.com/webstore/detail/quick-tabs/jnjfeinjfmenlddahdjdmgpbokiacbbb?hl=en) integrated into Saka Key would be great for navigating a large number of tabs.

**Comment by eejdoowad** [comment]
https://github.com/lusakasa/saka Is exactly what you’re looking for.
