### ISSUE TITLE
Feature Request: Provide user feedback when operation succesful

### ISSUE THREAD

**Issue by azzamsa** [lusakasa/saka-key#240]
Hi.

I am saka-key user in firefox. I use `yy` almost hundreds times a day, now I [expand it to `yo` too](https://github.com/lusakasa/saka-key/pull/238)

The problem is: when we want to navigate, visit link, etc we get feedback: hints shows up, page changed, etc. In `yy` (copy url) action we don't get user feedback if operation success, even if we had activated `Prevent Pages from Stealing Focus` sometimes `yy` failed.

it's painful to always check clipboard content if `yy` succeeded or failed.

My recommendation are: flash the tabs, blink the tab, or any other notification e.g [humane.js](https://github.com/wavded/humane-js), [react-notify-toast
](https://github.com/jesusoterogomez/react-notify-toast), so user know that the link copied successfully.

Thanks

**Comment by azzamsa** [comment]
for now. my solution is to use `Modified+key` instead of `key+key`. I think the former is more robust. the last always tend to fail.

**Comment by k0ral** [comment]
I second this feature request. I have been using Qutebrowser as my main browser for some time, testing Saka Key for a couple of hours to compare the keyboard-driven features, and feedback is what I miss the most at the moment. For example, on yanking current URL, Qutebrowser displays `Yanted URL to clipboard: <URL>` in the statusbar for a couple of seconds. It's simple, not disruptive, but it makes for a really pleasant user experience.

@joefiesta I don't feel comfortable enough with UX design to convince you that feedback on success is useful, but all the literature I've read about UX design goes into that direction, and my personal experience as a user can only confirm that.

**Comment by azzamsa** [comment]
Sorry, but I migrated to Vimium.
Feel free to reopen the issue if needed. But I can't provide any further comments.
