### ISSUE TITLE
[Feature] Duplicate as incognito

### ISSUE THREAD

**Issue by AdamPS** [lusakasa/saka-key#255]
Idea is to create a new incognito tab that is a duplicate of the current tab.  Thanks!

**Comment by AdamPS** [comment]
I guess it would be something like this in tabs.js

```
export async function duplicateAsIncognitoWindow () {
  await browser.windows.create({ url: document.location.href, incognito: true })
}

```

**Comment by AdamPS** [comment]
I posted a [bounty](https://www.bountysource.com/issues/73120244-feature-duplicate-as-incognito)

**Comment by AdamPS** [comment]
Excellent many thanks would be great to see a release containing this

**Comment by eejdoowad** [comment]
I’ll try to make a release this weekend. Thanks

**Comment by AdamPS** [comment]
Great thanks

**Comment by AdamPS** [comment]
Bounty has been paid out, good job done.  Would be great to have a new release please so I can use it:-)
