### ISSUE TITLE
some pages not working

### ISSUE THREAD

**Issue by dupontjoy** [lusakasa/saka-key#26]
for example: 
https://www.zhihu.com/explore
http://dig.chouti.com/

**Comment by eejdoowad** [comment]
This is a Firefox-only bug I think might be related to #24. Thanks for the examples. Still working on it, but I've been a little busy lately.

**Comment by dupontjoy** [comment]
thanks, hope saka gets better and better

**Comment by eejdoowad** [comment]
I've isolated the bug to window.handleDOMEvent (the function that passes events to Saka Key's modes) being inexplicably undefined despite a successful assignment at line https://github.com/lusakasa/saka-key/blob/master/src/client/modes.js#L45.

Installing event listeners is a little (too) complicated to satisfy all the requirements, and it seems like Firefox doesn't like how window.handleDOMEvent is redefined dynamically in a separate script.

In terms unrelated to Saka Key, this is the problem:

> Content script A adds an event listener L to the window which calls a function window.F I attached to the window. The content script loads another content script B which redefines the function window.F. Problem is, on some web pages this works fine, on others window.F is inexplicably undefined

**Comment by eejdoowad** [comment]
My latest commit should resolve this issue. I'll publish it to the dev channel of the add-ons marketplace shortly. If this problem persists, please let me know.
