### ISSUE TITLE
extension breaks the geico.com website

### ISSUE THREAD

**Issue by Willster419** [lusakasa/saka-key#280]
I'm not sure why, but it breaks the geico website.
I can provide you with debug logs if you need.

Using latest firefox

**Comment by xerus2000** [comment]
Try Inspect element -> there should be a div at the bottom of the XML with `id="saka-gui-root"` which lays itself over the whole page - if the site is styled weirdly or in combination with plugins like dark reader this can create issues.

Same issue on https://itsfoss.com/vector-graphics-editors-linux, which is completely covered by that element.

**Comment by xerus2000** [comment]
I have no issues on geico.com btw

**Comment by Willster419** [comment]
I had stopped using this extension a while ago, but i just installed it and in private mode it did not cause any issues. Here's what the inspect element looks like, if you still wanted it:

![image](https://user-images.githubusercontent.com/2482828/106851427-767b5b00-6673-11eb-8b65-823487a72832.png)
