### ISSUE TITLE
Saka-key extension not opening correctly

### ISSUE THREAD

**Issue by tenpoundhero** [lusakasa/saka-key#319]
Mac OS 11.12.1 and Firefox 85.0.2
When I open the extension it does not fully open correctly as seen in attached image. 
Haven't needed to click on the extension in a while so I'm not sure when this broke for me.
<img width="2556" alt="Screen Shot 2021-02-10 at 11 31 48 PM" src="https://user-images.githubusercontent.com/33327034/107602834-d7b5a800-6bf8-11eb-997f-c9247fefc6e3.png">

**Comment by tenpoundhero** [comment]
#127 @LinxiFan comment on Feb 11, 2018 gives a work around.

> I figured out. You have to open the option menu on a separate page instead of operating directly in the popup. You can do that from Firefox extension manager.

**Comment by yringot** [comment]
Or pull the saka button out of the Overflow menu. See my answer to a similar question here: https://github.com/lusakasa/saka-key/issues/320#issuecomment-876554924
