### ISSUE TITLE
Saka Key violates the Brave Web Store policy

### ISSUE THREAD

**Issue by barjoio** [lusakasa/saka-key#332]
Navigating to brave://extensions shows a message under the Saka Key item: "This extension violates the Brave Web Store policy."

Please see image below:

![image](https://user-images.githubusercontent.com/47948089/127410366-00eeec1f-0fe4-4801-85ec-b99806c38edf.png)

**Comment by npowdev** [comment]
Unfortunately, same on Chrome!

**Comment by pureooze** [comment]
Thanks for the report, please see https://github.com/lusakasa/saka-key/issues/331 I believe these are related.
