### ISSUE TITLE
Options export in Firefox hangs

### ISSUE THREAD

**Issue by ForgottenUmbrella** [lusakasa/saka-key#34]
When attempting to export settings from the Saka Key preferences page (from the Add-ons Manager page in Firefox, not the popup in the hamburger menu), the tab doesn't finish loading.
If I try to export settings from the popup (which the extension urges that it not be used), it works fine. The preferences page also works on Chrome, so this is a Firefox-specific issue.

I'm on Firefox 55, Saka Key 1.21.3.

**Comment by eejdoowad** [comment]
Thanks for the bug report again! Will work on a fix.

**Comment by ForgottenUmbrella** [comment]
Rather, I should be thanking you for creating this fantastic extension.
