### ISSUE TITLE
Key command to hard refresh

### ISSUE THREAD

**Issue by AndrewBelt** [lusakasa/saka-key#37]
On vanilla Firefox, Shift-Ctrl-R achieves a hard refresh. A saka-key binding would be great!

**Comment by eejdoowad** [comment]
Had no idea this existed. Definitely worthy of a command. I'll get to this eventually. The todo's backlog is huge. If you want to give it a shot, this is how:

1. Add a messaging command here: https://github.com/lusakasa/saka-key/blob/master/src/modes/command/client/commands/tab.js
2. Add the actual command here: https://github.com/lusakasa/saka-key/blob/master/src/modes/command/background/tab_commands.js#L169 using [this method](https://developer.chrome.com/extensions/tabs#method-reload)
3. Add an option here: https://github.com/lusakasa/saka-key/blob/master/src/options/Keybindings/config.json
4. Add default bindings here: https://github.com/lusakasa/saka-key/blob/master/src/options/Keybindings/default.json
