### ISSUE TITLE
Alt twice does not exit pass keys mode

### ISSUE THREAD

**Issue by willsALMANJ** [lusakasa/saka-key#38]
For me, pressing `alt` twice does not exit pass keys mode. I'm using version 1.21.3 on Firefox 55.0.3 on Linux. Maybe the key binding for exiting pass keys mode could be configurable? The best workaround I have found is to press `Ctrl+f` and then `Esc` which focuses and then blurs the find toolbar returning focus to Saka Key.

Perhaps #33 would solve this by providing a shortcut to enable/disable Saka Key. I'm not sure what the difference between pass keys mode and disabling Saka Key is.

**Comment by eejdoowad** [comment]
Using Alt to exit pass keys mode was a mistake since on Platforms other than Macs, Alt actually defocuses the viewport and focuses Chrome's setting's button, which results in the bug you documented. I'll make the key configurable.

This bug fix will also be part of the next release.
