### ISSUE TITLE
Hint appearance vertical padding misnamed

### ISSUE THREAD

**Issue by qaute** [lusakasa/saka-key#39]
There are two "Horizontal Padding (rem)" settings. The second acts as if it were "Vertical Padding (rem)"; it should probably be renamed.

![screenshot](https://user-images.githubusercontent.com/30400118/30004830-b90e1dba-909b-11e7-8151-0c8772780eb5.png)

**Comment by qaute** [comment]
*Saka Key 1.21.3 on Firefox 57.0a1 (2017-09-03) (64-bit)

**Comment by eejdoowad** [comment]
Thanks for the notice!  This will be fixed in the next release.
