### ISSUE TITLE
Some input fields can not be focused when using the preference to prevent pages stealing focus

### ISSUE THREAD

**Issue by willsALMANJ** [lusakasa/saka-key#40]
When the preference to prevent pages stealing focus is used, some input fields can not be focused using hints. Some examples:

1. www.google.com -- the main search box
2. www.duckduckgo.com -- the main search box
3. www.gmail.com -- click on "Sign in", then the "email or phone" box can not be selected.

When the focus stealing setting is off, these fields can be focused with hints.

With Vimium-FF, some pages would steal focus in a way that blocked all keys from working if the focus stealing preference was not on (see philc/vimium/issues/2613), so I just turned on in Saka Key to start out. I will leave it turned off now and see if Saka Kay handles these kinds of pages better.

**Comment by eejdoowad** [comment]
This should be fixed.  It'll be out in release 1.22.0.
