### ISSUE TITLE
Add a note on the AMO page: Add-on doesn't work on Firefox pages, not by addon's fault, but by Firefox's design

### ISSUE THREAD

**Issue by jayesh-bhoot** [lusakasa/saka-key#43]
Otherwise, the AMO page will be littered with 1-2 starred reviews - often understandably driven by VimFx nostalgia - thereby trashing the average rating. That would be disastrous when you are trying to fill the void left by VimFx.

The chances are some people still won't bother to read the description, but at least you would have done your part.

**Comment by eejdoowad** [comment]
Great advice. I've added a warning to the listing. Thanks!
