### ISSUE TITLE
Ctrl+[ not recogized as Escape character

### ISSUE THREAD

**Issue by adamryman** [lusakasa/saka-key#51]
From [Esc key - Wikipedia](https://en.wikipedia.org/wiki/Esc_key)

>  the Esc key (named Escape key in the international standard series ISO/IEC 9995) is a key used to generate the escape character (which can be represented as ASCII code 27 in decimal, Unicode U+001B, or `Ctrl+[`)

I use `Ctrl+[` as my escape key with `vim`, `vimperator`, `vimfx`, and chromes `vimium` and `cVim`. 

I would really like to use this with `saka-key` on firefox nightly (at time of writing firefox 58). 

It seems fire firefox has a default keybinding for `Ctrl+[` which switches tabs, I cannot find any extension for removing this keybinding for this version of firefox.

I would be happy to implement this. I would greatly appreciate being given a few files / line numbers to look at for implementing this. 

Two options I see:
- Add Escape key as a category in the keyboard config and add the implementing logic
- Quick and dirty: Add `Ctrl-[` as an escape key where ever `Escape` is currently being processed.

Thanks for the great plugin!

**Comment by eejdoowad** [comment]
Browsers don't actually support mapping one key to another. The substitute is to manually simulate the consequence of a keypress.

When you type a key, you generate a keyboard DOM event. Certain keyboard events cause the browser to perform some default built-in action (e.g. hitting the down arrow causes the page to scroll). The default action for `ctrl+[` is to navigate back in history.

Saka Key can prevent this default action. Mapping any command to `ctrl+[` will prevent the default action (navigating back in history) and execute the command instead.

The command behavior you desire is to trigger the escape key press. It's possible to create virtual keyboard events with Javascript.

`document.dispatch(new KeyboardEvent('keydown', { key: 'Escape' /* other attributes missing */ }))`

Once I've implemented custom commands, which is a work in progress, you'll be able to create a command that calls this Javascript. You'll then be able to map your custom Escape key command to `ctrl+[`.

Once thing you'll have to watch out for is that synthetic (Javascript) events DON'T trigger default behaviors. So if you have a select menu open, and you use the virtual Escape key command I wrote expecting the select menu to close, nothing will happen.

**Comment by eejdoowad** [comment]
If you'd like, you can go ahead and implement a virtual Escape keypress command following the instructions [here](http://key.saka.io/dev_docs/adding_commands). I think it's worth being built-in.

**Comment by troygnichols** [comment]
No idea when this changed, but `Ctrl + [` is currently working fine as an `Esc` key for me on Chrome 83.0.4103.97.

**Comment by adamryman** [comment]
@troygnichols , thanks for that information.

I just tested `Ctrl + [` and it is currently working fine as an `Esc` key in Firefox 98.0.1 (64-bit). 

Though it's sad that this plugin is unmaintained.
