### ISSUE TITLE
Disable "Search for text when you start typing" temporarily after using "f" to hint links?

### ISSUE THREAD

**Issue by bdfish** [lusakasa/saka-key#62]
Firefox57-beta4 + saka key 1.23.1

By default,`saka key`can not work if hint has two letters.

![peek 2017-10-02 10-08](https://user-images.githubusercontent.com/15389690/31062057-3ae06882-a75a-11e7-9011-934f216e53a3.gif)

After disable "Search for text when you start typing" in Firefox  preferences,everything goes well.

![peek 2017-10-02 10-09](https://user-images.githubusercontent.com/15389690/31062082-6eefb15a-a75a-11e7-883f-36fd37b57b57.gif)

**Comment by eejdoowad** [comment]
I never knew Firefox had this feature. Adding event.preventDefault() [here](https://github.com/lusakasa/saka-key/blob/f83a86cf7b6e6bc674958dd7455edae9833eeca8/src/modes/hints/client/index.js#L34) will fix it. This will make it into the next release.
