### ISSUE TITLE
toggle saka not working

### ISSUE THREAD

**Issue by y0y0z** [lusakasa/saka-key#69]
when i visit a webpage and i would like to toggle of saka, pressing `l` does not do the trick.

am i missing anything?
which information do you need me to post for you to be able to take a deeper look at the problem?

**Comment by eejdoowad** [comment]
I can see why you're confused. (Saka)[http://saka.io/] is a separate search bar extension, not Saka Key. If you install Saka, that command will toggle the search bar. I really need to make this more clear. There's no hotkey for disabling Saka Key, but there really should be one. I've just been sidetracked lately.

**Comment by y0y0z** [comment]
wow, *I WANT SAKA FOR FIREFOX!* (i wish everyone who read will vote up for this)

[vimfx](https://addons.mozilla.org/en-US/firefox/addon/vimfx/) binds `i` as a hotkey for disabling vimfx. that is, after hitting the `i` key, vimfx will not be triggered using any hotkey until it will be enabled back on when hitting the `i` again.

would be very much appreciate it if you could add such functionality to sara

**Comment by rfxDarth** [comment]
Can confirm, toggle saka doesn't work with bot saka and saka key addons installed on firefox 56.

By the way, isn't "Pass All Keys to Page" basically a disable hotkey?

**Comment by eejdoowad** [comment]
@rfxDarth, I should have mentioned that Saka for Firefox isn't really ready for use. The Pass All Keys to Page command is similar to disabling Saka Key temporarily for the current tab. A dedicated command would disable Saka Key on all tabs until reactivation.

**Comment by jayce-leathers** [comment]
I'm aware that Saka is in beta on FF but just in-case it helps, I can confirm that with saka and saka key installed in FF 57 Dev Edition, Saka toggle does not work. In fact Saka installed without Saka Key does not toggle either, not with any of the shortcuts.

**Comment by eejdoowad** [comment]
Heads up! Install Saka for Firefox at https://addons.mozilla.org/en-US/firefox/addon/saka-key/.
It doesn't integrate with Saka Key yet (So the L shortcut won't work until the next release of Saka Key). I've also open-sourced Saka at https://github.com/lusakasa/saka.
