### ISSUE TITLE
NEO2 keyboard layout breaks shortcuts

### ISSUE THREAD

**Issue by roSievers** [lusakasa/saka-key#71]
This happens in both Firefox and Chromium.

When using an alternative keyboard layout like NEO2 ("XVLCWK" instead of "QWERTY") the shortcuts will still assume the layout is QWERTY. I have to type "EE" which is on the "F" key to highlight hints. But once the the hints are highlighted I can to use the NEO2 layout again.

I tried to work around this, but changing the shortcuts broke the extension.

**Comment by plitter** [comment]
I had the same issue, by default the keys are hardwired to en-US QWERTY. It is possible to turn this of on the other hand though. By going to keybindings and deselecting "Bind to physical keys (en-US QWERTY) not characters".

**Comment by roSievers** [comment]
Thank you, this solves my problem. I'm closing this because it's not an issue.

**Comment by eejdoowad** [comment]
Enough people have complained about this that I think I chose the wrong default. It seems like binding to characters produces is the way to go.

**Comment by plitter** [comment]
I think it is an interesting choice and it is somethig I was considering when going from qwerty to dvorak programming layout on vim. When I changed the most annoying was that with vim the hjklfcx... etc. changed places, but if I did remap all the single key command keys I would have to remap all the keys and wouldn't help me learn it. It would also be a pain when it comes to the vim help. And i would have to have remember 2 sets of keys, qwerty for commands and dvorak for inserting.

I can only think of a single use case where this would be useful and it is if you were on a keyboard that was hardwired with different layout or your on a computer where you can't change your layout yourself.
