### ISSUE TITLE
Doesn't work in firefox 56.0.1 since update to 1.24.0

### ISSUE THREAD

**Issue by doronbehar** [lusakasa/saka-key#76]
The buttons don't work, nothing else is working, had to downgrade to `1.23.1`. Thought it should be reported.

**Comment by eejdoowad** [comment]
Thanks for the notice. I haven't been able to replicate this. I'm using Saka Key 1.24.0 on Firefox 55 and Firefox 57 dev edition. Do you by chance have custom settings? If you do, can you export them (using the options page's left side menu) and email the file to saka.help@gmail.com to help me debug the issue. Also, try upgrading back to 1.24.0 and resetting your settings (also from the options page)

**Comment by doronbehar** [comment]
Well I reinstalled it after I downgraded and everything seems to be OK. Thanks anyway.
