### ISSUE TITLE
Saka Key stops working due to options being wiped

### ISSUE THREAD

**Issue by SevereOverfl0w** [lusakasa/saka-key#90]
Opening a separate issue as it seems to be a different cause. Reference: https://github.com/lusakasa/saka-key/issues/89#issuecomment-339709730

I seem to be getting this from day to day (perhaps when suspending my laptop?). So I will likely report back tomorrow morning with the debugging output.

**Comment by eejdoowad** [comment]
It probably happens on days when I release updates, so you probably won't get it until then. Hopefully this will be fixed before the next update, so you won't get it at all.

It might be possible to replicate this by loading different version of Saka Key at https://addons.mozilla.org/en-US/firefox/addon/saka-key/versions/.

Are you sure the options are wiped? If this happens again try running `browser.storage.local.get().then(s=>console.log(s))` from the options page when you encounter this bug and copy and paste the results.

**Comment by SevereOverfl0w** [comment]
Given the recent release schedule, this looks very likely.

**Comment by joefiesta** [comment]
eejdoowad:

I don't understand what one is supposed to do if one wants to 
" try running browser.storage.local.get().then(s=>console.log(s)) from the options page when you encounter this bug and copy and paste the results."

**Comment by SevereOverfl0w** [comment]
@joefiesta I interpret instructions more precisely as:

1. Go to `about:addons`, hit "Preferences" on "Saka Key"
2. Right click anywhere, and hit "Inspect Element"
3. Click "Console" Tab in the opened window
4. Paste `browser.storage.local.get().then(s=>console.log(s))` into the text box at the very bottom of the screen

**Comment by joefiesta** [comment]
thanks SevereOverflow
way over my head (especially since I don't know java script or html or CSS !) but I greatly appreciate your clarification.

**Comment by SevereOverfl0w** [comment]
I survived the recent update without losing my config, so I'm assuming this is fixed.
